name: Deploy to GitHub Pages and Netlify

on:
  push:
    branches:
      - main

jobs:
  # 作业1：部署到 GitHub Pages（原逻辑）
  deploy-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: Build Hugo site
        run: hugo -F --cleanDestinationDir

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          PERSONAL_TOKEN: ${{ secrets.TOKEN }}
          EXTERNAL_REPOSITORY: Lingjia007/Hugo_Web
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public
          commit_message: ${{ github.event.head_commit.message }}

  # 作业2：构建并推送到 Netlify 分支
  deploy-to-netlify:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 需要写权限推送分支
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Switch to netlify branch
        run: git checkout -B netlify  # 强制创建/切换分支

      - name: Modify hugo.yaml for Netlify
        run: |
          # 替换第一行的部署 URL
          sed -i '1s#https://lingjia007.github.io/Hugo_Web/#https://lingsir007.netlify.app/#' hugo.yaml

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: Build Hugo site for Netlify
        run: |
          hugo -F --cleanDestinationDir  # 生成静态文件到 public 目录
          rm -rf ./en ./zh-hk  # 清理旧文件（如果存在）
          cp -r public/* ./     # 将静态文件移动到根目录

      - name: Push to Netlify branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          PERSONAL_TOKEN: ${{ secrets.TOKEN }}
          EXTERNAL_REPOSITORY: Lingjia007/Hugo_Web
          PUBLISH_BRANCH: netlify  # 推送到目标仓库的 netlify 分支
          PUBLISH_DIR: ./          # 推送根目录的构建结果
          commit_message: "Deploy to Netlify: ${{ github.sha }}"
