name: Deploy and Sync Netlify

on:
  push:
    branches:
      - main

jobs:
  # 原有部署到 GitHub Pages 的作业
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Git Configuration
        run: |
          git config --global core.quotePath false
          git config --global core.autocrlf false
          git config --global core.safecrlf true
          git config --global core.ignorecase false

      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: Build and Deploy
        run: |
          hugo -F --cleanDestinationDir
          mkdir -p public
          cp -r public/* ./

      - name: Copy static to en and zh-hk
        run: |
          mkdir -p en zh-hk
          cp -r static/* en/
          cp -r static/* zh-hk/

      - name: Copy assets to en and zh-hk
        run: |
          mkdir -p en zh-hk
          cp -r assets/* en/
          cp -r assets/* zh-hk/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          PERSONAL_TOKEN: ${{ secrets.TOKEN }}
          EXTERNAL_REPOSITORY: Lingjia007/Hugo_Web
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./
          commit_message: ${{ github.event.head_commit.message }}

  # 新增同步到 netlify 分支的作业
  sync-netlify:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 需要写权限推送分支
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main  # 确保检出的是原始 main 分支

      - name: Switch to netlify branch
        run: git checkout -B netlify  # 强制创建/切换分支

      - name: Modify hugo.yaml
        run: |
          # 使用 sed 替换第一行的 URL
          sed -i '1s#https://lingjia007.github.io/Hugo_Web/#https://lingsir007.netlify.app/#' hugo.yaml

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add hugo.yaml
          git diff --cached --quiet || git commit -m "Update Netlify URL in hugo.yaml"

      - name: Push to netlify branch
        run: git push origin netlify --force  # 强制推送覆盖
